Added node.js buildpack install
Install node.js into the slug as well as the build

Added a guard for lein-npm

Check for existing node dir before installing node

Revert cache dir stuff. better default task for lein npm

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -9,6 +9,21 @@ export BUILD_DIR=$1
 export CACHE_DIR=$2
 export ENV_DIR=$3
 
+# Install node.js
+install_nodejs() {
+  local version="$1"
+  local dir="$2"
+  local os="linux"
+  local cpu="x64"
+
+  echo "Downloading and installing node $version..."
+  local download_url="http://s3pository.heroku.com/node/v$version/node-v$version-$os-$cpu.tar.gz"
+  curl "$download_url" --silent --fail -o /tmp/node.tar.gz || (echo "Unable to download node $version; does it exist?" && false)
+  tar xzf /tmp/node.tar.gz -C /tmp
+  mv /tmp/node-v$version-$os-$cpu $dir
+  chmod +x $dir/bin/*
+}
+
 # Load config vars into environment
 export_env_dir() {
   env_dir=$1
@@ -39,6 +54,16 @@ install_java ${BUILD_DIR} ${javaVersion}
 jdk_overlay ${BUILD_DIR}
 echo "done"
 
+# Install Node.js
+if [ ! -d ${BUILD_DIR}/.heroku/nodejs ] && [ "true" != "$SKIP_NODEJS_INSTALL" ]; then
+  if [ "$(grep lein-npm $BUILD_DIR/project.clj)" != "" ] || [ -z "$NODEJS_VERSION"  ]; then
+    nodejsVersion=${NODEJS_VERSION:-4.2.1}
+    echo "-----> Installing Node.js ${nodejsVersion}..."
+    install_nodejs ${nodejsVersion} ${BUILD_DIR}/.heroku/nodejs 2>&1 | sed -u 's/^/       /'
+    PATH=${BUILD_DIR}/.heroku/nodejs/bin:$PATH
+  fi
+fi
+
 # Determine Leiningen version
 if [ "$(grep ":min-lein-version[[:space:]]\+\"2" $BUILD_DIR/project.clj)" != "" ]; then
   LEIN_VERSION="2.5.2"
@@ -46,6 +71,8 @@ if [ "$(grep ":min-lein-version[[:space:]]\+\"2" $BUILD_DIR/project.clj)" != "" 
   if [ "$(grep :uberjar-name $BUILD_DIR/project.clj)" != "" ]; then
       LEIN_BUILD_TASK="${LEIN_BUILD_TASK:-uberjar}"
       LEIN_INCLUDE_IN_SLUG="${LEIN_INCLUDE_IN_SLUG:-no}"
+  elif [ "$(grep lein-npm $BUILD_DIR/project.clj)" != "" ]; then
+      LEIN_BUILD_TASK=${LEIN_BUILD_TASK:-"with-profile production do deps, compile :all"}
   else
       LEIN_BUILD_TASK=${LEIN_BUILD_TASK:-"with-profile production compile :all"}
   fi
@@ -157,7 +184,7 @@ fi
 PROFILE_PATH="$BUILD_DIR/.profile.d/clojure.sh"
 mkdir -p $(dirname $PROFILE_PATH)
 echo "export LEIN_NO_DEV=\"\${LEIN_NO_DEV:-yes}\"" >> $PROFILE_PATH
-echo 'export PATH="$HOME/.jdk/bin:$HOME/.lein/bin:$PATH"' >> $PROFILE_PATH
+echo 'export PATH="$HOME/.heroku/nodejs/bin:$HOME/.jdk/bin:$HOME/.lein/bin:$PATH"' >> $PROFILE_PATH
 echo 'export RING_ENV="${RING_ENV:-production}"' >> $PROFILE_PATH
 
 # default Procfile
