Added detect failure message to stderr of bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -9,5 +9,6 @@ if [ -f $1/project.clj ]; then
     echo "Clojure" && exit 0
   fi
 else
-  echo "no" && exit 1
+  (>&2 echo "Could not find a 'project.clj' file! Please ensure it exists and is checked into Git.")
+  exit 1
 fi
