Add standard JVM buildpack Makefile (#180)

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,14 +1,13 @@
 #!/usr/bin/env bash
 # bin/use <build-dir>
 
-if [ -f $1/project.clj ]; then
-  grep ":min-lein-version[[:space:]]\+\"2" $1/project.clj > /dev/null
-  if [ $? -eq 0 ]; then
-    echo "Clojure (Leiningen 2)" && exit 0
-  else
-    echo "Clojure" && exit 0
-  fi
+if [ -f "$1/project.clj" ]; then
+	if grep ":min-lein-version[[:space:]]\+\"2" "$1/project.clj" >/dev/null; then
+		echo "Clojure (Leiningen 2)" && exit 0
+	else
+		echo "Clojure" && exit 0
+	fi
 else
-  (>&2 echo "Could not find a 'project.clj' file! Please ensure it exists and is checked into Git.")
-  exit 1
+	(>&2 echo "Could not find a 'project.clj' file! Please ensure it exists and is checked into Git.")
+	exit 1
 fi
